### PR TITLE
Allow providing height for poster plugin

### PR DESCRIPTION
**Pull request by fratzinger**
It's the same behaviour as for `filepond-plugin-image-preview`. I introduced three new properties:
prop | equivalent
------|-------
filePosterHeight | imagePreviewHeight
filePosterMinHeight | imagePreviewMinHeight
filePosterMaxHeight | imagePreviewMaxHeight

The underlying img-element is not absolute anymore but `height: 100%; width: auto;`

I also added `index.d.ts` types.
It's tested with various dimensions

this closes:
- #10
- pqina/vue-filepond#94
- pqina/filepond-plugin-file-poster#7

changes also documented: pqina/filepond-docs#12

### CODE REVIEW

**Comment by rikschennink** [comment]
Thanks! Will run some tests on Monday 👍

**Comment by rikschennink** [comment]
Looks good 👍 

Can you change the default value for `filePosterMaxHeight` to `null` devs can then opt-in to the new behaviour.

**Comment by fratzinger** [comment]
Great. Of course. I changed it to keep the behaviour. 
Also changed it pqina/filepond-docs#12 :)

**Comment by nehadhiman6** [comment]
Thank You for adding new properties :)

**Comment by MansourM** [comment]
UPDATE:
i have downloaded the raw js,css file from github repo releaes, which is way behind for some reason, please update gifthub repo releases :)

filePondHeight is not working for me, i make the pond like this:

```js
pond = FilePond.create(inputElement, {
                        labelIdle: 'drop here',
                        imagePreviewHeight: 200,
                        filePosterHeight: 200,
                    }
```

later i add options and load the poster
```js
pond.setOptions({
            files: [
                {
                    // the server file reference
                    source: '12345',

                    // set type to local to indicate an already uploaded file
                    options: {
                        type: 'local',

                        // optional stub file information
                        file: {
                            name: 'my-file.png',
                            size: 3001025,
                            type: 'image/png',
                        },

                        // pass poster property
                        metadata: {
                            poster: '/file/download/passport-1.png',
                        },
                    },
                },
            ],
        });
```
it loads the image but height is way more than 200
what am i doing wrong?

**Comment by wasappi** [comment]
Same behaviour for me, setting `filePosterHeight` to a specific value but my poster is still way too big

**Comment by wasappi** [comment]
> UPDATE: i have downloaded the raw js,css file from github repo releaes, which is way behind for some reason, please update gifthub repo releases :)
> 
> filePondHeight is not working for me, i make the pond like this:
> 
> ```js
> pond = FilePond.create(inputElement, {
>                         labelIdle: 'drop here',
>                         imagePreviewHeight: 200,
>                         filePosterHeight: 200,
>                     }
> ```
> 
> later i add options and load the poster
> 
> ```js
> pond.setOptions({
>             files: [
>                 {
>                     // the server file reference
>                     source: '12345',
> 
>                     // set type to local to indicate an already uploaded file
>                     options: {
>                         type: 'local',
> 
>                         // optional stub file information
>                         file: {
>                             name: 'my-file.png',
>                             size: 3001025,
>                             type: 'image/png',
>                         },
> 
>                         // pass poster property
>                         metadata: {
>                             poster: '/file/download/passport-1.png',
>                         },
>                     },
>                 },
>             ],
>         });
> ```
> 
> it loads the image but height is way more than 200 what am i doing wrong?

Make sure to import filepond-plugin-file-poster.css

**Pull request merged**
